### ISSUE TITLE
Help Request: dot command doesn't execute anything

### ISSUE THREAD

**Issue by yacosta738** [gtrabanco/dotSloth#210]
I tried to use sloth but the documentation is not clear at all.

I need help with some basic examples. 

When I execute the command dot -v  the output is 

`dot -v`

```bash
 dot - graphviz version 3.0.0 (0)
libdir = "/usr/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.so.6
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.so.6
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        /usr/lib/graphviz/config6![bitmoji](https://sdk.bitmoji.com/render/panel/02919870-550c-48e9-b644-df89ae03584e-db1ffc10-9e7f-4bea-a043-e744f59d5043-v1.png?transparent=1&palette=1&width=246)
                was successfully loaded.
    render      :  cairo dot dot_json fig gd json json0 map mp pic pov ps svg tk visio vml vrml xdot xdot_json
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  canon cmap cmapx cmapx_np dot dot_json eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tk vdx vml vmlz vrml wbmp webp x11 xdot xdot1.2 xdot1.4 xdot_json xlib
    loadimage   :  (lib) eps gd gd2 gif jpe jpeg jpg png ps svg webp xbm
```

I tried to migrate my archlinux dotfiles to Sloth but currently, I have problems with the basics of sloth.

Exist for some basic tutorials? #209 

![bitmoji](https://sdk.bitmoji.com/render/panel/02919870-550c-48e9-b644-df89ae03584e-db1ffc10-9e7f-4bea-a043-e744f59d5043-v1.png?transparent=1&palette=1&width=246)

**Comment by gtrabanco** [comment]
That dot is not this dot. If you are trying to install it with brew you should install with exactly these instructions:

```bash
brew tap gtrabanco/tools
brew install gtrabanco/tools/dot
```

You can see the steps here: https://twitter.com/slothfiles/status/1477657832493391874

**Comment by gtrabanco** [comment]
Anyway the recommended version to have the latest version available you should install it as dependency in your dotfiles folder, this can be done automatically by using the installer script.

The steps are described in the README.

**Comment by yacosta738** [comment]
I tried to install and use Sloth in Manjaro OS and work fine, but in my archlinux PC, the dot command doesn't work. What dependencies use Sloth?

**Comment by gtrabanco** [comment]
You can see them in the project path: `scripts/core/src/install.sh`

Probably I am assuming that any package should be installed only in Debian distributions? 😅

Can be also that any package is not available through pacman. The only good package managers implementations are brew and aptitude.

There is algo missing installer for FreeBSD.

**Comment by yacosta738** [comment]
For Archlinux and Arch distributions the package python-yq is [yq](https://archlinux.org/packages/community/any/yq/) , [docopts](https://aur.archlinux.org/packages/docopts)

```bash
sudo pacman -S python-pip yq
```

**Comment by gtrabanco** [comment]
Ok I'll fix it soon. Thank you! 🙏
